---

- name: Converge
  hosts: airflow_group
  roles:
    - role: idealista.airflow_role
  environment:
    AIRFLOW_HOME: "{{ airflow_app_home }}"
    AIRFLOW_CONFIG: "{{ airflow_conf_path }}/airflow.cfg"
