---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False

platforms:
  - name: airflow-${MOLECULE_DISTRO:-stretch}
    image: debian:${MOLECULE_DISTRO:-stretch}
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - airflow
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: False
