---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: airflow
    groups:
      - airflow_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
    stop_signal: 'RTMIN+3'
    exposed_ports:
      - 8088/tcp
      - 8080/tcp
      - 8081/tcp
      - 5000/tcp
      - 5555/tcp
    published_ports:
      - 0.0.0.0:8088:8088/tcp
      - 0.0.0.0:8080:8080/tcp
      - 0.0.0.0:8081:8081/tcp
      - 0.0.0.0:5000:5000/tcp
      - 0.0.0.0:5555:5555/tcp

provisioner:
  name: ansible

scenario:
  name: default

verifier:
  name: ansible
