---
# This is an example playbook to execute goss tests.
# Tests need distributed to the appropriate ansible host/groups
# prior to execution by `goss validate`.

- name: Verify airflow
  hosts:
    - airflow
  become: true
  vars:
    goss_version: v0.4.9
    goss_arch: "{{ 'amd64' if ansible_facts.architecture == 'x86_64' else 'arm64'}}"
    goss_dst: /usr/local/bin/goss
    goss_url: "https://github.com/goss-org/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: /tmp
    goss_format: documentation

  vars_files:
    - ../../defaults/main/main.yml
    - ../../defaults/main/airflow-cfg.yml
    - ../../defaults/main/webserver-config-py.yml
    - ./group_vars/airflow_group/main.yml

  tasks:
    - name: Download and install Goss
      ansible.builtin.get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        checksum: "sha256:{{ goss_url }}.sha256"
        mode: 0755
      register: download_goss
      until: download_goss is succeeded
      retries: 6

    - name: Copy Goss tests to remote
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ goss_test_directory }}/{{ item | basename }}"
        mode: '0644'
      with_fileglob:
        - "tests/test_*.yml"

    - name: Register test files
      ansible.builtin.shell: "ls {{ goss_test_directory }}/test_*.yml"
      register: test_files

    - name: Execute Goss tests
      ansible.builtin.command: "{{ goss_dst }} -g {{ item }} validate --format {{ goss_format }} --retry-timeout 10s"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the Goss results
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      ansible.builtin.fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
